config:
  icloud:
    users:
      - user: your_apple_id
        password: your_apple_id_password
  calendar:
    client_id: your.google.calendar.client.id
    client_secret: your_google_calendar_client_secret
  weather:
    api_key: your_dark_sky_api_key
